### ISSUE TITLE
Node v4 is not actually supported

### ISSUE THREAD

**Issue by lars-t-hansen** [tc39/ecmarkup#112]
The problem is a phrase in lib/cli.js, `for (const [file, watcher] of watching) ...` which is probably too-new JS for Node v4.  Node v7.4.0 works for me, but it would probably be better if the TypeScript compiler could translate the phrase to Node v4 compatible JS.

**Comment by bterlson** [comment]
Hmm good call. I can change just change typescript's target I suppose.
