### ISSUE TITLE
`--js` and `--css` do not omit JS and CSS from resulting HTML file.

### ISSUE THREAD

**Issue by ljharb** [tc39/ecmarkup#119]
`ecmarkup --js=spec.js --css=spec.css index.html` creates the `.js` and `.css` files, but then seems to *also* populate `index.html` with all the same JS and CSS that's included in the separate files.

**Comment by bakkot** [comment]
This seems to have gotten fixed at some point; closing. Feel free to reopen if I'm mistaken.
