### ISSUE TITLE
Allow setting document language (`<html lang>`)

### ISSUE THREAD

**Issue by jordanbtucker** [tc39/ecmarkup#127]
Ecmarkup outputs documents without a `lang` attribute on the `html` element. (In fact, it doesn't output `<html>` tags at all, which is fine when no `lang` attribute is needed.)

Ecmarkup should accept a `language` document option to support this. For example:

```html
<pre class=metadata>
repository: https://github.com/bterlson/ecmarkup
assets: none
copyright: false
language: en
</pre>
```

It would also be nice if `<html>` tags were parsed in the document itself. For example: 

```html
<html lang="en">
<pre class="metadata">
repository: https://github.com/bterlson/ecmarkup
assets: none
copyright: false
</pre>
...
</html>
```

This is the only warning that [https://checker.html5.org](https://checker.html5.org/?doc=https%3A%2F%2Fbterlson.github.io%2Fecmarkup%2F) outputs for Ecmarkup documents.

**Comment by bakkot** [comment]
As of #224, ecmarkup will preserve the `html` tag when it has attributes such as `lang`. I don't think there's much need to have explicit metadata for the language beyond `<html lang="en">`, so I'm going to call this fixed.
