### ISSUE TITLE
Multipage builds

### ISSUE THREAD

**Issue by devsnek** [tc39/ecmarkup#151]
A multipage build of ECMA-262 is oft requested by those of us with potato devices.

Inspiration can be taken from the html spec:

https://html.spec.whatwg.org/multipage/

- Each major section of the spec (as seen in "Table of Contents") becomes a separate page
  - 262 has way more top-level sections than html. Too many? the right amount? unknown at this time.
  - Should related sections like 1, 2, 3 be turned into a single page?
- Cross linking is handled by rewriting links based on a large json file
  - https://html.spec.whatwg.org/xrefs.json
  - https://github.com/whatwg/html/blob/master/html-dfn.js

**Comment by cup** [comment]
https://github.com/bterlson/ecmarkup/issues/151
https://github.com/tc39/ecma262/issues/1270
https://github.com/tc39/ecma262/issues/1434

**Comment by leobalter** [comment]
There are two problems when people read this:

- the source (spec.html) is too big and we could split it to many files
- the rendered version is a single page and takes to long to load and it's not lovely to browse.

Both of these together seems like the easiest way to handle this, but there are other blocking concerns for the former as we can see in the issues referenced here.

I understand this issue targets the latter, but I wonder how we'd best handle multipage rendering out a single source file. Html  seems to do that already, but it requires machinery that works for ecmarkup.

If we try the multipage, I'd suggest following something else html does, also continue building the single page version.

This is not an easy work but requires someone to dedicate a good effort. IMO, it's hard to justify this usage of time. Maybe someone else can afford this?

**Comment by ljharb** [comment]
We could split the rendered page by top-level section numbers, for example,

**Comment by devsnek** [comment]
Made a little demo by postprocessing the spec: https://snek.dev/ecma262-multipage-demo/multipage/

After playing with it for a bit I think a separate page for each numbered/lettered section is good, even if the first few sections are a bit small. The one awkward part was manually putting the "contributing to this specification" and "introduction" into the index instead of on their own separate pages, but I assume with the data from the biblio that can be automated.

**Comment by leobalter** [comment]
It looks very good so far.
