### ISSUE TITLE
Grammar nodes copy-paste without whitespace

### ISSUE THREAD

**Issue by bakkot** [tc39/ecmarkup#248]
Because we use CSS margins to pad grammar nodes and do not include any actual whitespace, copy/pasting productions gives you all the text smooshed together without spaces. We should add some whitespace.

**Comment by bakkot** [comment]
Ref: https://github.com/rbuckton/grammarkdown/issues/27

**Comment by michaelficarra** [comment]
It also makes searching for grammar hard because you have to search without the whitespace. Most readers probably won't know this.
