### ISSUE TITLE
Automatically update ecma262biblio.json

### ISSUE THREAD

**Issue by bakkot** [tc39/ecmarkup#251]
This file is meant to allow proposals which refer to parts of ECMA262 (say, a grammar production) to automatically link to the relevant part of 262, just as if they'd been included in the spec itself. But it's very stale. We should publish the file as its own package and have a script on https://github.com/tc39/ecma262 which updates and publishes a new minor version of that package whenever a commit is added to the main branch of that repository, then add it as either a dependency of this package or a dev-dependency of the proposal template.

**Comment by ljharb** [comment]
Why does it need to be published as opposed to just referenced from the ecma262 repo?

**Comment by bakkot** [comment]
As in, have proposals point to the github repo? I suppose that would also work, but generally I prefer to use the npm registry to manage dependencies, since that is the usual way of doing things.

**Comment by ljharb** [comment]
that'll be a lot of overhead in the ecma262 branch tho, unless we can add CI to require an updated biblio to be in each PR, and even then we'd want a version tag for every bump of that package, which would add a lot of commits to ecma262 just for that purpose.

**Comment by bakkot** [comment]
We don't need any of that. The biblio file doesn't need to be committed and doesn't need to live in any repository. We can just have a Travis job or whatever which regenerates the biblio file and its package.json and publishes it whenever ecma262 master is pushed.

**Comment by ljharb** [comment]
I suppose that would address my concerns, but it seems problematic to me to be publishing a package that has no git sha associated with it.

**Comment by bakkot** [comment]
We can put the ecma262 sha in a README.md in the package.

**Comment by ljharb** [comment]
true, or even populate the package's "repository" link with a direct link to the sha, or something.

**Comment by bakkot** [comment]
It's common practice to have your repository contain source files and have your published package contain build artifacts, e.g. the output of babel or whatever. This doesn't seem particularly different.

**Comment by rbuckton** [comment]
I created https://github.com/tc39/ecma262/issues/2321 in the ecma262 repository for this, as ecmarkup isn't the only tool that could benefit from being able to fetch an up-to-date `ecma262biblio.json` file.

**Comment by rbuckton** [comment]
I've been thinking about dusting off my VSCode plugin for ecmarkup (I already started tinkering with it again a few months ago). One of the things I'd love to be able to do is have the ability to "Insert a spec section" into the current document. That would essentially give you a list of searchable section names in the biblio, then fetch the source for the section and insert it at the cursor location so that you can start editing.

**Comment by bakkot** [comment]
Biblio is available on npm as  [@tc39/ecma262-biblio](https://www.npmjs.com/package/@tc39/ecma262-biblio). Proposals can add it as a dependency and use the new `--load-biblio` to link against it.
