### ISSUE TITLE
`emu-grammar` tag content incorrect

### ISSUE THREAD

**Issue by rbuckton** [tc39/ecmarkup#253]
While trying to render the spec for https://tc39.es/proposal-class-access-expressions/#sec-left-hand-side-expressions, it seems like ecmarkup is trying to slice the content of the grammar from the node location. However, the node comes from an imported file (via `<emu-import>`) and all of the slices are coming from the root file (index.html), so none of the content is correctly passed.

**Comment by bakkot** [comment]
Published ecmarkup@4.1.2 with the fix.
