### ISSUE TITLE
Consider allowing "If" line ending in "; then"

### ISSUE THREAD

**Issue by ptomato** [tc39/ecmarkup#354]
Consider the example,

> 1. If _a_, _b_, and _c_ are all 0; or _d_, _e_, and _f_ are all 0; then

The semicolon seems punctuationally correct here, since it's a [semicolon acting as a 'super-comma' separating phrases containing commas of their own](https://english.stackexchange.com/a/349246/634), but the linter complains:

> expected "If" with substeps to end with ", then" (found " are all 0; then")

Not a big deal by any means, but maybe worth considering allowing this?

**Comment by michaelficarra** [comment]
I see how the first semicolon in your example is a "super-comma", but I still think the second one should be a comma. Do you have a better reference to show the appropriate punctuation for that position?

**Comment by bakkot** [comment]
@michaelficarra In general, in English, we can use a semicolon to when joining (using a conjunction) clauses containing commas. Here's a few links:
- https://www.niu.edu/writingtutorial/punctuation/semicolon.shtml#:~:text=Semicolons%20used%20to%20replace%20commas
> Use a semicolon to replace a comma when you use a coordinating conjunction to link independent clauses that already contain commas.


- https://writing.wisc.edu/handbook/grammarpunct/semicolons/
> Use a semicolon between independent clauses joined by a coordinating conjunction if the clauses are already punctuated with commas or if the clauses are lengthy.


- https://www.ox.ac.uk/sites/files/oxford/media_wysiwyg/University%20of%20Oxford%20Style%20Guide.pdf
> Use semicolons in place of commas in a complicated list or sentence if it will improve clarity, particularly if list items already include commas.
