### ISSUE TITLE
[contiguous] syntactic RHS annotation

### ISSUE THREAD

**Issue by js-choi** [tc39/ecmarkup#356]
A new [contiguous] RHS syntactic annotation will probably be required in at least two proposals:
* The [Hack-pipe proposal will use it to distinguish `^=` as `^` [contiguous] `=`](https://github.com/js-choi/proposal-hack-pipes/issues/13).
* The [decorators proposal will probably use it between `@` and decorator expressions](https://github.com/tc39/proposal-decorators/issues/430), as well as [within `@init:` and after](https://github.com/tc39/proposal-decorators/issues/431#issuecomment-909262060).

ecmarkup currently seems to have a hard-coded set of accepted RHS annotations, like [lookahead] and [no LineTerminator]. This means that any [contiguous] in an `<emu-grammar>` disappears, which requires manually re-adding  `<emu-gann>[contiguous]</emu-gann>` at its original position. It would be nice if [contiguous] were handled by ecmarkup, too, in order to handle this for Hack pipes and for decorators.

**Comment by bakkot** [comment]
The grammar is actually defined in [grammarkdown](https://github.com/rbuckton/grammarkdown), not ecmarkup.

That said, I'm not convinced this is the right approach to solve the problems you've highlighted.

For decorators, we ought to be able to just define a `Decorator` token along the lines of `@ IdentifierName`. This would be a single token, like [PrivateName](https://tc39.es/ecma262/multipage/ecmascript-language-lexical-grammar.html#prod-PrivateIdentifier), and would therefore not allow whitespace.

For `|> ^=`, I'm less certain. However, I believe you can fix this by introducing a new goal symbol for the [lexical grammar](https://tc39.es/ecma262/multipage/ecmascript-language-lexical-grammar.html#sec-ecmascript-language-lexical-grammar) which specifies whether a `^` is lexed as the pipeline topic variable or as the XOR operator. That is, just as it currently uses `InputElementRegExp` and `InputElementDiv` to distinguish whether to lex `/` as the beginning of a regular expression or as division, it could have a `InputElementPipelineTopic` and `InputElementXor` to distinguish whether to lex `^` as the pipeline topic variable or as the XOR operator.

**Comment by js-choi** [comment]
Hack pipes no longer need a [contiguous] annotation (js-choi/proposal-hack-pipes#20), so I’ll be closing this. There might still be some issues with decorators (see https://github.com/tc39/proposal-decorators/issues/431#issuecomment-912977921), but we can open a new issue in grammar grammarkdown if we end up needing [contiguous] for that.
