### ISSUE TITLE
Determine draft date by the last modified date of the ecmarkup

### ISSUE THREAD

**Issue by ljharb** [tc39/ecmarkup#390]
Specifically, in a proposal, every time I run `ecmarkup spec.emu index.html`, the HTML updates with the current date, even if the ecmarkup hasn't changed.

Can the date generated be "when the input was modified" and not "the current date", to reduce diff churn?

**Comment by arhadthedev** [comment]
I think the author date of a commit is better. It allows anyone to checkout any revision at any moment and render it with a correct first line ("Draft ECMA-262 / Xxx yy, zzz"). Also, file dates are lost on transfer if a is file not archived first on a source.

**Comment by ljharb** [comment]
There’s no necessarily any commit at the time, so there’s no commit info to load.

If it used last modified date, then checking out an older revision would still use the proper date.

**Comment by bakkot** [comment]
I'm reluctant to look at modification times on disk, since that's fiddly to do correctly, but we can probably come up with some kind of solution here.

If the concern is just diff churn, though, it seems like the simplest thing would be to just keep the build output on a different branch which you never look at? That's what 262 does and it works great.

**Comment by ljharb** [comment]
That doesn't allow one to seamlessly check out older versions.

**Comment by bakkot** [comment]
I don't know what that means. You can check out an older version and build it just fine.

**Comment by ljharb** [comment]
Sure, but then you have to build it. I want to be able to hop quickly through the rendered diffs, and have the rendering changes and the source changes be done in the same/adjacent commit.

**Comment by bakkot** [comment]
Hmm. It's not usual practice to commit build artifacts, but given how slow `npm install` is I can understand wanting to avoid that, if it comes up a lot.

If ecmarkup supported [the SOURCE_DATE_EPOCH property](https://reproducible-builds.org/specs/source-date-epoch/) from the reproducible builds people (so you could do `SOURCE_DATE_EPOCH=$(date -r in.emu '+%s') ecmarkup in.emu out.html`), would that work for you?

**Comment by ljharb** [comment]
Absolutely that'd be fine, thanks!

**Comment by arhadthedev** [comment]
> but given how slow npm install is

I found that `node_modules` [can be cached by setup-node Github Action](https://github.com/actions/setup-node#caching-packages-dependencies):

> The action has a built-in functionality for caching and restoring dependencies. It uses actions/cache under hood for caching dependencies but requires less configuration settings. Supported package managers are npm, yarn, pnpm (v6.10+). The cache input is optional, and caching is turned off by default.

So I guess the following modification is required for `publish.yml`:

```diff
       - name: Setup node
         uses: actions/setup-node@v2
         with:
           node-version: '16'
           registry-url: 'https://registry.npmjs.org'
+          cache: 'npm'
```

**Comment by ljharb** [comment]
@arhadthedev that doesn’t apply locally.
