### ISSUE TITLE
Latest ecmarkup reports duplicate AO errors for Temporal AOs superseded in 402

### ISSUE THREAD

**Issue by justingrant** [tc39/ecmarkup#394]
The Temporal spec contains [some AOs](https://tc39.es/proposal-temporal/#sup-temporal-calendar-abstract-ops) that have 262 versions and 402 versions that's used in implementations that support 402. ecmarkup 9.7.0 reports errors for these AOs. Version 8.0.1 did not report these errors. How should we handle?

Here's a repro in the [proposal-temporal](https://github.com/tc39/proposal-temporal) repo:

```
npm i ecmarkup@9.7.0
justingrant@jgmac proposal-temporal % npm run build:spec

> proposal-temporal@1.0.0 prebuild:spec
> mkdirp out


> proposal-temporal@1.0.0 build:spec
> ecmarkup --lint-spec --strict spec.html out/index.html

[2021-12-15T02:31:34.072Z] Error: spec/intl.html:1306:9: duplicate definition "IsBuiltinCalendar"
[2021-12-15T02:31:36.113Z] Exiting with an error due to errors (omit --strict to write output anyway)
[2021-12-15T02:31:36.114Z] Rerun with --verbose to see detailed error information
```

**Comment by bakkot** [comment]
Choose one of them to be canonical and omit the `aoid` from the other one. Uses of `IsBuiltinCalendar` can only link to a single place, so having `aoid` be present on both is ambiguous.

(Previously, or if you omit `--strict`, it was last-wins, mostly by accident.)

**Comment by justingrant** [comment]
Sounds good, thanks @bakkot!  Closing this issue now.
