### ISSUE TITLE
change algorithm step numbering to use list-style-type and @counter-style

### ISSUE THREAD

**Issue by michaelficarra** [tc39/ecmarkup#417]
We can implement the algorithm step numbering a lot nicer with [`list-style-type`](https://developer.mozilla.org/en-US/docs/Web/CSS/list-style-type) and [`@counter-style`](https://developer.mozilla.org/en-US/docs/Web/CSS/@counter-style).

**Comment by bakkot** [comment]
Done. [Retroactively, even.](https://github.com/tc39/ecmarkup/blob/05d05f71e1bc8cf151da65d34e9105eff3e7d465/css/elements.css#L186)

**Comment by michaelficarra** [comment]
I think I was thinking of how we generate step references, oops.
