### ISSUE TITLE
formatter should translate HTML entities to code points where possible

### ISSUE THREAD

**Issue by bakkot** [tc39/ecmarkup#477]
cf https://github.com/tc39/ecma262/issues/404#issuecomment-1218537924

See also https://github.com/tc39/ecmarkup/issues/476.

Note to self: this should not include blank codepoints like `&nbsp;` or `&lrm;`. "blank" [probably](http://www.unicode.org/faq/unsup_char.html) means "[Control](https://util.unicode.org/UnicodeJsps/list-unicodeset.jsp?a=[:General_Category=Control:]), [White_Space](https://util.unicode.org/UnicodeJsps/properties.jsp?a=White_Space), or [Default_Ignorable](https://util.unicode.org/UnicodeJsps/list-unicodeset.jsp?a=[:Identifier_Type=Default_Ignorable:])", in Unicode terms. (Linked page does not include "Control" but it seems an obvious thing to add; it is not a subset of DI, per [its definition](https://unicode.org/reports/tr44/#Default_Ignorable_Code_Point), and indeed `\u0000` is not DI.)

Also there's 93 entities which expand to multiple code points, often including a variation selector or "U+0338 COMBINING LONG SOLIDUS OVERLAY". Should exclude any multi-code point ligatures where at least one code point is blank in the above sense, and probably any which include combining characters (i.e. `gc=M`).

I.e. exclude anything which expands to a sequence of code points which matches `/\p{White_Space}|\p{DI}|\p{gc=M}|\p{gc=C}/u`.

**Comment by ljharb** [comment]
Additionally, can the linter require the formatter's output in this case?

**Comment by bakkot** [comment]
There's a `--check` flag to the formatter which asserts that the input is already formatted in the form which would be output by the formatter, which is intended to serve that purpose. (We [use that in CI](https://github.com/tc39/ecma262/blob/cd0692b082e9092a5b64aa5a8ba6ebb48161bfb2/.github/workflows/enforce-format.yml#L17) on 262.)
