### ISSUE TITLE
Skip `<del>` tags when counting number of AO parameters

### ISSUE THREAD

**Issue by ptomato** [tc39/ecmarkup#491]
The parameter counter doesn't handle markup like this very well:

https://github.com/tc39/proposal-temporal/pull/2245/files#diff-cd62efd2602bdd5c2e435179e40c5d2daa5db198c9ac6324a6f8cf1c41a89873R73-R82

It thinks the AO should be called with 4 or 5 parameters, whereas it should be 3 or 4. One of the parameters is inside a `<del>` tag, hence the discrepancy.

**Comment by ptomato** [comment]
(A likely-looking workaround is `<del>_excludedItems_</del><ins>_excludedKeys_</ins>: a List of property keys,`, or `_excluded<del>Items</del><ins>Keys</ins>_: ...`, but neither of those are accepted by the structured header parser.)

**Comment by bakkot** [comment]
Fixed in 15.0.1.
