### ISSUE TITLE
Superscript text representing exponents is not copy-paste safe

### ISSUE THREAD

**Issue by gibson042** [tc39/ecmarkup#516]
Elements such as `<sup>` in data copied from spec content are replaced with their textContent when pasting as plain text, which can result in semantically inappropriate transformations such as (plucking real-word cases from [Number.prototype.toFixed](https://tc39.es/ecma262/multipage/numbers-and-dates.html#sec-number.prototype.tofixed)) "If x ≥ 10<sup>21</sup>" → "If x ≥ 1021" and "n / 10<sup>f</sup> - x" → "n / 10f - x".

This is a common need when writing test262 tests (cf. https://github.com/tc39/test262/blob/main/CONTRIBUTING.md#info ), so we should try to improve the experience similarly to what was done for step labels in #290.

**Comment by bakkot** [comment]
What's the thing you think it should copy as? For digits I can map to the Unicode subscripts/superscripts, but obviously that doesn't generalize.

**Comment by gibson042** [comment]
I'm thinking [up-arrow notation](https://en.wikipedia.org/wiki/Knuth%27s_up-arrow_notation) for elements that can't be translated directly. PR incoming.
