### ISSUE TITLE
False-positive definition link in Temporal spec

### ISSUE THREAD

**Issue by justingrant** [tc39/ecmarkup#518]
In the [Temporal spec](https://tc39.es/proposal-temporal), the source HTML `DST-safe` is turned into the following markup:

```html
DST-<emu-xref href="#safe-integer"><a href="https://tc39.es/ecma262/#safe-integer">safe</a></emu-xref>
```

This definition link is obviously wrong, and is not present in the source:

https://github.com/tc39/proposal-temporal/blob/0141b153110f7ab4595c5bdd08af6407d7c07f6b/spec.html#L16

Are we doing something wrong in our use of `ecmarkup`?  

<img width="612" alt="image" src="https://user-images.githubusercontent.com/277214/218876275-0d7afec6-5e7d-4a6f-abd0-54b5a7520dc7.png">

**Comment by bakkot** [comment]
You're not doing anything wrong, but that's just how ecmarkup works - any use of a defined term links to that term. And 262 defines the term "safe". It probably shouldn't but as long as it does, you can use [emu-not-ref](https://tc39.es/ecmarkup/#emu-not-ref) to prevent it from linking.

**Comment by justingrant** [comment]
Excellent, thanks Kevin for the pointer to [emu-not-ref](https://tc39.es/ecmarkup/#emu-not-ref). We'll use that for this case.

Perhaps ecmarkup shouldn't treat `-` as a word delimiter?

**Comment by bakkot** [comment]
Yeah, maybe. On the other hand, a lot of times it is - `non-finite` linking "finite", etc, generally makes sense.

**Comment by justingrant** [comment]
I did a quick look for `\w-<emu-xref` in the current 262 and 402 specs' markup and found 17 matches. All of them looked valid except this one:
<img width="486" alt="image" src="https://user-images.githubusercontent.com/277214/218887685-f506d155-60e9-4875-be4f-065ce17aecb8.png">

Perhaps auto-linking could be improved via a whitelist of specific frequently-used prefixes, after only which auto-linking would be allowed?  Here's the prefixes used for the valid auto-links in the current specs that look OK:
* per-
* mullti-
* single-
* non-
* inter-

**Comment by justingrant** [comment]
`/` might be another questionable delimiter. Found a few `emu-not-ref`s used in the Temporal spec to avoid "date/time values" from being linked.

**Comment by bakkot** [comment]
Since it seems like most instances of `-word` are cases where it should be linked, I am loathe to add hardcoded special cases here. I'd prefer to stick with `emu-not-ref` for the less common cases when it shouldn't link, I think.

**Comment by justingrant** [comment]
Sound good to me. I filed https://github.com/tc39/ecma262/pull/3014 to fix the one missing emu-not-ref in the existing 262 spec. Closing this issue.
