### ISSUE TITLE
`declared` vs. `<ins>` or `<del>`

### ISSUE THREAD

**Issue by justingrant** [tc39/ecmarkup#528]
When `[declared="s"]` is wrapped in an `<ins>` or `<del>`, it no longer works. 

Example: 
```
1. <ins>[declared="s"] Let _systemTimeZoneString_ be the String representing the host environment's current time zone, either a primary time zone identifier or a String _s_ for which ParseText(StringToCodePoints(_s_), |NormalizedUTCOffset|) returns a Parse Node.</ins>
```

Expected: OK

Actual: could not find a preceding declaration for "s"

The same text works fine if I remove the `<ins>`.

**Comment by bakkot** [comment]
I suspect it will work if you put the `[declared="s"]` outside of the `<ins>`.

**Comment by justingrant** [comment]
Cool, that works. Thanks!

**Comment by bakkot** [comment]
I think actually fixing changing the behavior here is going to be more trouble than it's worth, so I [documented it as a restriction instead](https://tc39.es/ecmarkup/#variable-declarations). Going to close as wontfix for the moment.
