### ISSUE TITLE
Double-indented text does not produce a warning

### ISSUE THREAD

**Issue by justingrant** [tc39/ecmarkup#536]
From https://github.com/tc39/proposal-temporal/pull/2621#discussion_r1245364044:

The following spec text did not produce any complaints from ecmarkup. I would have expected that only one additional level of indentation (two spaces) is allowed.

```
      1. Else if _parseResult_ contains a |UTCOffsetSubMinutePrecision| Parse Node, then
          1. Let _offset_ be the source text matched by the |UTCOffsetSubMinutePrecision| Parse Node contained within _parseResult_.
          1. Set _timeZoneResult_.[[OffsetString]] to CodePointsToString(_offset_).
```

**Comment by bakkot** [comment]
Handling of whitespace is generally managed by the [formatter](https://github.com/tc39/ecmarkup#formatter), not the build job, and indeed if you run the formatter on this input it will fix it for you.

**Comment by justingrant** [comment]
Oh!  Got it, sorry for the spam. The spec workflow in the Temporal repo has never used the formatter, but as we get closer to Stage 4 we should start using it. Issue opened. Thanks!
