### ISSUE TITLE
consider linting against camelCase enum values

### ISSUE THREAD

**Issue by bakkot** [tc39/ecmarkup#544]
`~enums~` are written with inconsistent casing within and across specs. https://github.com/tc39/ecmarkup/pull/539 will change the styling to smallcaps, which can look a little bit weird with capital letters, so that might be a good impetus to start enforcing `~kebab-case~` enum values everywhere.

cc @tc39/ecma402-editors because this would entail a change in 402 (which has some kebab-case, some camelCase, and some enum values with spaces).

**Comment by gibson042** [comment]
I have no objection to changing spec-internal enum values for better internal consistency.
