### ISSUE TITLE
commit snapshot banner obscures bottom of references pane

### ISSUE THREAD

**Issue by michaelficarra** [tc39/ecmarkup#547]
![image](https://github.com/tc39/ecmarkup/assets/218840/2322165f-2698-4c2f-939f-6bcaa8b22f66)

Instead of being a fixed overlay, the banner should probably have its own reserved viewport space so it doesn't cover anything.

**Comment by bakkot** [comment]
Snapshot banner lives in 262: https://github.com/tc39/ecma262/blob/68881b6ce4c688e71499b435a8dac4ac0d4e7681/scripts/insert_snapshot_warning.js

**Comment by michaelficarra** [comment]
➡️ https://github.com/tc39/ecma262/issues/3158
