### ISSUE TITLE
consider adding indentation spaces to hidden spec steps for copy-paste

### ISSUE THREAD

**Issue by michaelficarra** [tc39/ecmarkup#551]
That way we get step numbers and they are indented relative to each other properly.

**Comment by bakkot** [comment]
Ideally only when you've selected multiple lines, though.

**Comment by michaelficarra** [comment]
This one might be tricky since we want to preserve *relative* indentation, but we don't necessarily want a copied segment to all be excessively indented just because it is deeply nested. I'm not sure how to do that other than hijacking the copy with JavaScript.

**Comment by bakkot** [comment]
Yeah I was imagining [hijacking the copy](https://developer.mozilla.org/en-US/docs/Web/API/Element/copy_event).

**Comment by gibson042** [comment]
Was this fixed by #604?

**Comment by bakkot** [comment]
Yup, thanks!
