### ISSUE TITLE
should permit iterating a List without declaring a binding

### ISSUE THREAD

**Issue by michaelficarra** [tc39/ecmarkup#566]
I want to be able to iterate a List using the `For each element _e_ of _list_, do` notation without having to declare an unused binding (essentially, repeat this a number of times equal to the number of elements in the list). I would write this as `For each element of _list_, do`, but ecmarkup currently thinks that declares `_list_` instead of referencing it.

**Comment by ljharb** [comment]
Why not a loop from 0 to list.length?

**Comment by michaelficarra** [comment]
It's not as direct.

**Comment by bakkot** [comment]
I also prefer a loop from 0 to the length of the list, and so am not going to implement this.

**Comment by michaelficarra** [comment]
We talked about this in editor call and are going to explore using "Repeat _n_ times:" as an alternative.

**Comment by michaelficarra** [comment]
I get this error when using the suggested form:

> Error: spec.emu:47:14: expected "Repeat" to start with "Repeat, while " or "Repeat, until "

**Comment by bakkot** [comment]
https://github.com/tc39/ecmarkup/pull/567
