### ISSUE TITLE
Should spec constants be uppercased by `build` rather than CSS?

### ISSUE THREAD

**Issue by gibson042** [tc39/ecmarkup#621]
It's a bit odd that text at e.g. [NormalCompletion](https://tc39.es/ecma262/multipage/ecmascript-data-types-and-values.html#sec-normalcompletion) has a step that _looks like_ "Return Completion Record { [[Type]]: NORMAL, [[Value]]: value, [[Target]]: EMPTY }." but _copies as_ "Return Completion Record { [[Type]]: normal, [[Value]]: value, [[Target]]: empty }." (because [`text-transform`](https://drafts.csswg.org/css-text/#text-transform-property) "_has no effect on the underlying content, and must not affect the content of a plain text copy & paste operation_").

It would probably reduce surprise (and increase the value of copy–paste interactions for purposes such as test262) to perform uppercasing at build time such that it is part of the resulting HTML source:
```diff
-{ <var class="field">[[Type]]</var>: <emu-const>normal</emu-const>, <var class="field">[[Value]]</var>: <var>value</var>, <var class="field">[[Target]]</var>: <emu-const>empty</emu-const>&nbsp;}
+{ <var class="field">[[Type]]</var>: <emu-const>NORMAL</emu-const>, <var class="field">[[Value]]</var>: <var>value</var>, <var class="field">[[Target]]</var>: <emu-const>EMPTY</emu-const>&nbsp;}
```

**Comment by bakkot** [comment]
The alternative is for them to copy as `~empty~`, with tildes added in, to better match the source rather than the display. See https://github.com/tc39/ecmarkup/issues/550.

**Comment by gibson042** [comment]
Ah yeah, that's probably better.
