### ISSUE TITLE
How do I specify a setter?

### ISSUE THREAD

**Issue by ljharb** [tc39/ecmarkup#630]
`<h1>set Error.prototype.stack ( _value_ )</h1>` errors with
> error: expected operation to have a name like 'Example', 'Runtime Semantics: Foo', 'Example.prop', etc, but found "set Error.prototype.stack " (header-format) 

In other words, it accepts `>get foo<` but not `>set foo ( _arg_ )<`

**Comment by bakkot** [comment]
Setters are specified using a different syntax than functions. See for example the [Iterator.prototype.constructor](https://tc39.es/ecma262/multipage/control-abstraction-objects.html#sec-iterator.prototype.constructor) setter.

**Comment by ljharb** [comment]
aha, thanks
