### ISSUE TITLE
normative-optional reprentation

### ISSUE THREAD

**Issue by caridy** [tc39/ecmarkup#96]
At TC39, there was consensus that normative-optional can be denoted by putting a box around the optional parts, rather than out-of-line as in Annex B, as long a the denotation of normative-optional was the same.

@bterlson what's the recommendation for such construction? should we add something to ecmarkup?

**Comment by caridy** [comment]
backpointer https://github.com/tc39/ecma402/pull/84#issuecomment-207120916

**Comment by caridy** [comment]
@bterlson this is the issue that I mentioned today. The initial proposal is to introduce `<emu-clause normative-optional>`.

**Comment by littledan** [comment]
How is this work going? I'm currently blocking https://github.com/tc39/ecma402/pull/84 on it. It would be really nice to get this in relatively soon. I could rephrase the patch with "old style" Annex B if needed, but it's unfortunate to keep the 402 spec in a web-incompatible state as it is now.

**Comment by bterlson** [comment]
@littledan sorry I missed your ping. I didn't realize this was blocking work :(

Currently we have emu-annex which is non-normative by default and optionally normative using a `normative` attribute. I suppose we can allow a range of values for this attribute: "" is default, "true" is normative, "false" is non-normative, and "optional" is normative-optional.

Next question is how to display it. I would propose that we display either "non-normative" or "normative-optional" under the section headers (normative would be assumed otherwise). Thoughts?

We should also probably describe what these concepts mean in a separate clause in 262...

**Comment by bterlson** [comment]
Also ecmarkup being a superset of html means you can roll your own solution any time. If an emu-clause begins with the text "this clause is optionally normative" then that's probably good enough for now.

**Comment by littledan** [comment]
In the case of this ECMA402 change, the normative optional text is a couple steps within an algorithm, rather than an emu-clause.

**Comment by bterlson** [comment]
Hmmmm... so what are you thinking then? A new block element for switching normativity of prose? Something like `<emu-normativity optional/non-normative>`?

**Comment by littledan** [comment]
Yeah, something like that. Maybe we could even render this with a colored line on the side when viewing it on the web, like many web specs do (e.g. generated from Bikeshed)

**Comment by bterlson** [comment]
Have a link to Bikeshed's presentation of normative-optional handy?

**Comment by littledan** [comment]
We're the only ones who are into this normative-optional stuff as far as I know :) Here's an example: [in the W3C permissions spec draft](https://w3c.github.io/permissions/#permission-descriptor), you can see WebIDL in blue, and an example in yellow. There are also issues in red, and notes in green, in the same document. Would it be possible to style an algorithm step something like that? We could insert text for the printed version like NORMATIVE OPTIONAL: at the beginning of the line.

**Comment by spectranaut** [comment]
Between 2017 and 2018, we lost the block for "normative-optional" steps in an ECMA-402 algorithm: 
- [2017](https://www.ecma-international.org/ecma-402/4.0/index.html#sec-unwrapdatetimeformat)
- [2018](https://www.ecma-international.org/ecma-402/5.0/index.html#sec-unwrapdatetimeformat)

@bterlson can we add a `<emu-normative-optional>` feature, styled like the 2017 spec? Was there one once that was lost?

**Comment by spectranaut** [comment]
nevermind, somehow I missed that this has been fixed in 2019. you can close this issue :)

**Comment by littledan** [comment]
Wow, good catch @spectranaut ! I do hope we can get this feature upstream in ecmarkup, so we can avoid using the HTML hacks I put into ECMA-402, as well as address accessibility issues with those hacks that @bterlson raised but I lack the expertise to address properly.

**Comment by bakkot** [comment]
Fixed by #292, which introduces a new `normative-optional` attribute which can be applied to clauses (and only clauses). Feel free to open a new issue if there's more needed.
